### ISSUE TITLE
Update description text for validation statuses

### ISSUE THREAD

**Issue by robredpath** [IATI/validator-web#599]
@simon-20 after conversations in Bogotá I changed my mind about not updating the text in https://github.com/IATI/validator-web/blob/2de392f3bf667d7442c28da4ed1293354f407059/src/components/FileStatusInfo.vue - it clearly is more confusing than helpful. 

I'll make a suggestion below - feedback welcome. @stevieflow @IsabelBirds @siwhitehouse in particular might have views on this. 

(with appropriate links before we go live, obviously) 

****

Validation includes testing the file against the [IATI XML Schema](#) and the [IATI Rulesets](#). For more information, see [IATI Validation Methodology](#)

Success - file uses the IATI standard with no errors, warnings or advisories
Success (with Advisories) - file uses the IATI standard with no errors or warnings, but there are ways that it could be more useful
Warning - file passes XML schema validation, but does not pass all IATI rulesets that state that a condition "should" be met
Error - file passes XML schema validation, but does not pass all IATI rulesets that state that a condition "must" be met
Critical - data does not pass XML schema validation and therefore does not appear in the [IATI Datastore](#) and may be missing from other tools

**Comment by IsabelBirds** [comment]
Current messages for context

* Success - file is valid with no errors of any type, congratulations!
* Warning - data can be more valuable and warnings should be corrected when possible.
* Error - data is hard or impossible to use.
* Critical - data contains significant errors, none or not all of the data can be used by tools or accessed by the [IATI Datastore](https://iatidatastore.iatistandard.org/)

I think Critical should be made extra clear e.g.

Critical - Data does not pass XML schema validation. Data will not update in the [IATI Datastore](https://github.com/IATI/validator-web/issues/599#). Data may be unusable and/or missing from other tools.

**Comment by robredpath** [comment]
Let's go for:

----

This file has been tested against the IATI Standard XML Schema, and the IATI Standard Rulesets. For more information, see the [documentation](https://docs.validator.iatistandard.org).

The validation statuses are:

Success - No errors, warnings or advisories
Success (with Advisories) - No errors or warnings, but there are advisories relating to potential issues with the data
Warning - XML Schema validation passes, but not all IATI ruleset rules stating that a condition "should" be met
Error - XML schema validation passes, but not all IATI ruleset rules stating that a condition "must" be met
Critical - XML schema validation fails. This means that data will not update in the [IATI Datastore](https://datastore.iatistandard.org). Data may be unusable and/or missing from other tools.

@simon-20

**Comment by robredpath** [comment]
This is now changed
